version: '3.8'

services:
  bitwarden:
    image: bitwarden/server:latest # Changed from bitwarden/self-host:latest
    container_name: bitwarden
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./bw-data:/etc/bitwarden
      - ./logs:/var/log/bitwarden
    environment:
      # --- REQUIRED BITWARDEN CONFIGURATION ---
      - globalSettings__baseServiceUri__vault=https://bitwarden.yourdomain.com # REPLACE with your actual domain
      - globalSettings__internalServiceUri__vault=http://postgresql-database-bitwarden # Internal Docker network name for the database service
      - globalSettings__installationId=YOUR_INSTALLATION_ID_HERE # **REPLACE WITH YOUR ID FROM bitwarden.com/host**
      - globalSettings__installationKey=YOUR_INSTALLATION_KEY_HERE # **REPLACE WITH YOUR KEY FROM bitwarden.com/host**

      # --- DATABASE CONFIGURATION ---
      - globalSettings__sqlServer__connectionString=Host=postgresql-database-bitwarden;Port=5432;Database=bitwarden_vault;Username=postgres;Password=sCMH1tWAZ5HpIoxC4z3Bpe9Jr46zNFPkjqFXQphT9IhD7jtRHZ1Nt1JjVmUyR0Xe;Pooling=true;Encrypt=true;TrustServerCertificate=true;
      - globalSettings__database__type=PostgreSql

    depends_on:
      - postgresql-database-bitwarden

  postgresql-database-bitwarden:
    image: postgres:16-alpine
    container_name: bitwarden-db
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bitwarden_vault
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sCMH1tWAZ5HpIoxC4z3Bpe9Jr46zNFPkjqFXQphT9IhD7jtRHZ1Nt1JjVmUyR0Xe
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  bw-data:
  logs:
  pg-data:
